<?php
/**
 * @file
 *
 * Serv dynmaic content based on hostname
 */

/**
 * Implements hook_menu().
 */
function odaa_domain_menu() {
  $items = array();

  $items['css'] = array(
    'title' => 'CSS',
    'page callback' => 'odaa_domain_serv_file',
    'page arguments' => array('css'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['scripts'] = array(
    'title' => 'Scripts',
    'page callback' => 'odaa_domain_serv_file',
    'page arguments' => array('scripts'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['images'] = array(
    'title' => 'Images',
    'page callback' => 'odaa_domain_serv_file',
    'page arguments' => array('images'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['font'] = array(
    'title' => 'Font',
    'page callback' => 'odaa_domain_serv_file',
    'page arguments' => array('font'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}

/**
 * Serv theme css file.
 */
function odaa_domain_serv_file($type) {
  $file = arg();
  array_shift($file);
  $file = implode('/', $file);
  $file_path = drupal_get_path('theme', $GLOBALS['theme_key']) . '/' . $type . '/' . $file;
  if (file_exists($file_path)) {
    $output = file_get_contents($file_path);

    drupal_add_http_header('Content-Type', file_get_mimetype($file_path));
    echo $output;
    return;
  }
}

/**
 * Implements hook_form_system_site_information_settings_alter().
 *
 * Add field to filter content base on ckan organization.
 */
function odaa_domain_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['site_information']['ckan_organization'] = array(
    '#type' => 'textfield',
    '#title' => t('CKAN Organization'),
    '#description' => t('The name/string used to filter on organizations in ckan (e.g. aarhus-kommune).'),
    '#default_value' => variable_get('ckan_organization', ''),
  );
}

