<ul class="main-menu">
  <li><a href="#" class="menu-item"><span>Forsiden</span></a></li>
  <li><a href="#" class="menu-item"><span>Datasæt</span></a></li>
  <li><a href="#" class="menu-item"><span>Organisation</span></a></li>
  <li><a href="#" class="menu-item"><span>Grupper</span></a></li>
  <li><a href="#" class="menu-item"><span>App</span></a></li>
  <li><a href="#" class="menu-item"><span>Om</span></a></li>
</ul>