<div class="newsletter-signup">
  <form action="http://odaa.us5.list-manage1.com/subscribe/post?u=78ef4b94a7d1865894df78e68&amp;id=28f6dabe60" method="post" name="mc-embedded-subscribe-form" class="newsletter-form validate" target="_blank" novalidate="">
    <h2>Tilmeld dig vores nyhedsbrev</h2>
    <div class="newsletter-field-group">
      <input type="email" value="" name="EMAIL" class="email newsletter-field required" placeholder="Email adresse" />
      <input type="submit" value="Tilmeld" name="subscribe" class="button submit-button newsletter-button" />
    </div>
  </form>
</div>