<div class="powered-by">
	<p><strong>Powered by</strong></p>
	<a href="http://ckan.org" title="ckan The open source data portal software"><img class="footer-logo first" src="../../images/ckan-footer-logo.png" alt="ckan logo" title="Powered by ckan" /></a>
	<a href="http://drupal.org" title="An open source content management platform powering millions of websites and applications"><img class="footer-logo last" src="../../images/drupal-footer-logo.png" alt="Drupal logo" title="Powered by Drupal" /></a>
</div>