<div class="sub-menu-wrapper">
  <h2 class="sub-menu-title">Om ODAA</h2>
  <ul class="sub-menu">
    <li><a href="#" class="menu-item"><span>FAQ</span></a></li>
    <li><a href="#" class="menu-item"><span>Kontakt</span></a></li>
    <li><a href="#" class="menu-item"><span>Vilkår og betingelser</span></a>
      <ul class="sub-menu">
        <li><a href="#" class="menu-item"><span>Underpunkt</span></a></li>
        <li>
          <a href="#" class="menu-item"><span>Underpunkt</span></a>
          <ul class="sub-menu">
            <li><a href="#" class="menu-item active"><span>Underpunkt</span></a></li>
            <li><a href="#" class="menu-item"><span>Underpunkt</span></a></li>
            <li class="last"><a href="#" class="menu-item"><span>Underpunkt</span></a></li>
          </ul>
        </li>
        <li class="last"><a href="#" class="menu-item"><span>Nyhedsbrev</span></a></li>
      </ul>
    </li>
    <li><a href="#" class="menu-item"><span>Something else</span></a></li>
    <li class="last"><a href="#" class="menu-item"><span>Open Source</span></a></li>
  </ul>
</div>